name: Run My Project

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: List files
        run: ls -la

      - name: Run app
        run: python app.py